config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts

  root :to => 'pages#home'
  
  get "about" => 'pages#about'
  get "posts" => 'posts#index'
  get "contact" => 'pages#contact'

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_footer.html.erb
<%= link_to "Contact me", contact_path %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <div class="navbar-brand"><%= link_to "Principals of Dating", root_path %></div>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Posts", posts_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <% if user_signed_in? %>
                <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-nav' %>
                <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-nav' %>
              <% else %>
                <%= link_to "Role Call", new_user_session_path, :class => 'navbar-nav' %>
              <% end %>
            </li>
            </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/views/layouts/application.html.erb
<%= render "layouts/navbar" %>

<!DOCTYPE html>
<html>
<head>
  <title>PrincipalsOfDating</title>
  <%= csrf_meta_tags %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</head>
<body>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<%= render "layouts/navbar" %>

<div class="container">
  <div class="jumbotron">
    <h1>About "Miss Wormwood"</h1>
    "Miss Wormwood" is a sadistic woman, whose identity needs to be protected, who has been on the dating scene for probably closing in on half a century now.  She also works as an assistant principal, and uses this title to assist in her quest for the complete annihilation of the male psyche.
  </div>
</div>

app/views/pages/contact.html.erb
<%= render "layouts/navbar" %>

<div class="container">
  <div class="jumbotron">
    <h1>Contact Miss Wormwood</h1>
Have you learned NOTHING from this site?  DO NOT CONTACT MISS WORMWOOD!!!
  </div>
</div>

app/views/pages/home.html.erb
<%= render "layouts/navbar" %>
<div class="container">
  <div class="jumbotron">
    
    <h1>Principals of Dating</h1>

    <body>
    <p>If you want to read about my debaucherous adventures, head over to my posts, and I promise you'll end up feeling like a half-way decent person in comparison!</p>
    </body>
  </div>
  <%= render "layouts/footer" %>

</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, :size => 75 %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content, :size => "150x13" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<%= render "layouts/navbar" %>

<div class="container">
  <div class="jumbotron">
    <h1>Editing post</h1>
  

  <%= render 'form' %>

  <%= link_to 'Show', @post %> |
  <%= link_to 'Back', posts_path %>
</div></div>

app/views/posts/index.html.erb
<%= render "layouts/navbar" %>

<div class="container">
  <div class="jumbotron">
    <h1>Miss Wormwood's Hijinx</h1>
    <table class="fixed">
      <thead>
        <tr>
          <th width="75px">Date</th>
          <th>Title</th>
          <th colspan="5"></th>
        </tr>
      </thead>

      <tbody>
        <% @posts.each do |post| %>
          <tr>
            <td><%= post.created_at.strftime("%m-%d-%Y") %> --</td>
            <td><%= link_to post.title, post %> </td>
            <% if signed_in? %>
 
              <td>| <%= link_to 'Edit', edit_post_path(post) %> | </td>
              <td><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>

    <br>
    <% if signed_in? %>
      <%= link_to 'New Post', new_post_path %>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<%= render "layouts/navbar" %>

<div class="container">
  <div class="jumbotron">
    <h1><%= @post.title %></h1>
    <h4>
      <i>By Miss Wormwood</i>
    </h4>
    <br>
    <p>
      <%= @post.content %>
    </p>
    <% if signed_in? %>
    <%= link_to 'Edit', edit_post_path(@post) %> |
    <% end %>
    <%= link_to 'Back', posts_path %>
  </div>
</div>